<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MazEdit.Tests/**" />
    <None Remove="MazEdit.Tests/**" />
    <EmbeddedResource Remove="MazEdit.Tests/**" />
  </ItemGroup>

</Project>
